apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: nylas-api
    labels: 
        app: nylas-api
spec:
    replicas: 3
    template:
        metadata:
            labels:
                app: nylas-api
        spec:
            containers:
                name: nylas-api
                image: gcr.io/nylas-sync-engine-148809/nylas-image
                command: ['inbox-api']